name: Frontend

on:
  push:
    branches: [ develop ]
    paths:
      - 'frontend/**'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on:  ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      
      - name: Install dependency
        working-directory: ./frontend
        run: npm ci --legacy-peer-deps

      - name: Build Next.js app
        working-directory:  ./frontend
        env:
          NEXT_PUBLIC_API_URL: https://api.pearlinvest.click
        run:  npm run build

      - name: Configure AWS CLI for NCP
        run:  |
          aws configure set aws_access_key_id ${{ secrets.NCR_ACCESS_KEY }}
          aws configure set aws_secret_access_key ${{ secrets.NCR_SECRET_KEY }}
          aws configure set default.region kr-standard
        
      - name: Deploy to Object Storage
        working-directory: ./frontend
        run: |
          export AWS_RESPONSE_CHECKSUM_VALIDATION=when_required
          export AWS_REQUEST_CHECKSUM_CALCULATION=when_required
          aws s3 sync out/ s3://woosupar-multi-cloud/frontend \
            --endpoint-url=https://kr.object.ncloudstorage.com \
            --delete